### ISSUE TITLE
sorting

### ISSUE THREAD

**Issue by HorstBaumann** [froemken/repair_translation#5]
great extension !
But there is one small bug: **it ignores the sorting of the files.**
I fixed it by adding **sorting_foreign** to the query in /repair_translation/Classes/SignalSlot/Repair.php :

original:
`$rows = $this->getDatabaseConnection()->exec_SELECTgetRows(
            '*',
            'sys_file_reference',
            implode(' AND ', $where)
        );`

new:
`$rows = $this->getDatabaseConnection()->exec_SELECTgetRows(
            '*',
            'sys_file_reference',
            implode(' AND ', $where),
            '',
            'sorting_foreign'
        );`

**Comment by froemken** [comment]
Hello @HorstBaumann 

Thank you for your hint. It is already solved at master, but I have never pushed it to TER.
I have just released version 1.1.0 which should be available within the next 15 Minutes at TER and Packagist.

Please test that version and give me feedback if you want.

Stefan

**Comment by HorstBaumann** [comment]
It works fine :-)
Thanks for updating this great extension !!!
(it's a shame, that it is still necessary and the core-bug still exists...)
